# 1. Numpy array creation

In [1]:
import numpy as np

In [3]:
l1 = [1,2,3,4,5]

In [4]:
arr1 = np.array(l1)

In [5]:
l1

[1, 2, 3, 4, 5]

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1+9

array([10, 11, 12, 13, 14])

In [8]:
l1+l1

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
arr1+arr1

array([ 2,  4,  6,  8, 10])

In [10]:
l2 = [ [2,4,6,8],[1,3,5,7] ]

In [11]:
arr2 = np.array(l2)

In [85]:
arr2[0,0] = 4
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [86]:
l2

[[2, 4, 6, 8], [1, 3, 5, 7]]

In [87]:
arr3 = np.array(arr2,dtype='float')

In [88]:
arr3

array([[4., 4., 6., 8.],
       [1., 3., 5., 7.]])

In [89]:
arr2 = np.array(arr3,dtype='int')

In [90]:
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [91]:
arr4 = np.array(arr2,dtype='bool')

In [92]:
arr4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [93]:
#heterogeneous type array
arr5 = np.array([2,5,2.5,True],dtype='object')

In [94]:
arr5

array([2, 5, 2.5, True], dtype=object)

In [95]:
l3 = arr5.tolist()

In [96]:
l3

[2, 5, 2.5, True]

In [97]:
type(arr1)

numpy.ndarray

# 2. Array Dimensions

In [98]:
arr2.shape

(2, 4)

In [99]:
arr2.size

8

In [100]:
arr2.dtype

dtype('int32')

In [101]:
arr2.ndim

2

# 3. Reversing Rows and Columns

In [102]:
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [103]:
arr2[::-1] #reversing rows

array([[1, 3, 5, 7],
       [4, 4, 6, 8]])

In [104]:
arr2[::,::-1] #reversing columns

array([[8, 6, 4, 4],
       [7, 5, 3, 1]])

In [105]:
arr2[::-1,::-1] #reversing rows and columns both

array([[7, 5, 3, 1],
       [8, 6, 4, 4]])

In [106]:
arr2.T #transpose

array([[4, 1],
       [4, 3],
       [6, 5],
       [8, 7]])

# 4. Specific Element Extraction

In [107]:
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [108]:
arr2[0,:] #first row

array([4, 4, 6, 8])

In [109]:
arr2[:1,:] #till first row

array([[4, 4, 6, 8]])

In [110]:
arr2[:2,:] #first 2 rows

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [111]:
arr2[:-1,:] #except last row

array([[4, 4, 6, 8]])

In [112]:
arr2[-1,:] #last row

array([1, 3, 5, 7])

In [113]:
arr2[:,1:3] #all rows, 0 and 1 column 

array([[4, 6],
       [3, 5]])

# 5. Basic Statistics

In [114]:
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [115]:
arr2.max()

8

In [116]:
arr2.min()

1

In [117]:
arr2.sum()

38

In [118]:
arr2.mean()

4.75

In [119]:
np.median(arr2)

4.5

In [120]:
np.average(arr2)

4.75

In [121]:
np.var(arr2)

4.4375

# 6. Reshaping and Flattening

In [122]:
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [123]:
arr2.shape

(2, 4)

In [124]:
arr2.reshape(4,2)

array([[4, 4],
       [6, 8],
       [1, 3],
       [5, 7]])

In [125]:
arr2.reshape(8,1)

array([[4],
       [4],
       [6],
       [8],
       [1],
       [3],
       [5],
       [7]])

In [126]:
f1 = arr2.flatten()

In [127]:
f1 #1d array of arr2

array([4, 4, 6, 8, 1, 3, 5, 7])

In [128]:
f1.ndim

1

# 7. Creating Random numbers and sequences

In [129]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [132]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [133]:
np.linspace(1,99,3) #both 1 and 99 and inclusive here, automatic step size

array([ 1., 50., 99.])

In [134]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [135]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [137]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
np.zeros([2,2,2,])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

# 8. Unique elements and count

In [139]:
arr2

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

In [140]:
np.unique(arr2)

array([1, 3, 4, 5, 6, 7, 8])

In [141]:
np.unique(arr2,return_counts=True)

(array([1, 3, 4, 5, 6, 7, 8]), array([1, 1, 2, 1, 1, 1, 1], dtype=int64))

# 9. Sorting

In [143]:
np.sort(arr2) #each row sorted

array([[4, 4, 6, 8],
       [1, 3, 5, 7]])

# 10. Searching

In [144]:
arr2==3

array([[False, False, False, False],
       [False,  True, False, False]])

In [149]:
np.where(arr2==3) #indexe tuple

(array([1], dtype=int64), array([1], dtype=int64))

In [152]:
np.where(arr2==4)

(array([0, 0], dtype=int64), array([0, 1], dtype=int64))

In [159]:
np.where(arr2%2==0)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

# 11. Filtering

In [160]:
arr2[arr2==4]

array([4, 4])

In [161]:
arr2[arr2%2==0]

array([4, 4, 6, 8])